# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nm', models.IntegerField(default=0)),
                ('core', models.IntegerField(default=0)),
                ('thread', models.IntegerField(default=0)),
                ('clock', models.FloatField(default=0)),
                ('l3', models.IntegerField(default=0)),
                ('tdp', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.FloatField(default=0)),
                ('rpm', models.IntegerField(default=0)),
                ('buffer', models.IntegerField(default=0)),
                ('thickness', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mainboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chipset', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('pcie_slot', models.IntegerField(default=0)),
                ('sata3', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('w', models.IntegerField(default=0)),
                ('a', models.IntegerField(default=0)),
                ('pin4_ide', models.IntegerField(default=0)),
                ('sata', models.IntegerField(default=0)),
                ('pin6plus2_pci_e', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=50)),
                ('use', models.CharField(max_length=50)),
                ('dimm', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('clock', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('clock', models.IntegerField(default=0)),
                ('b_clock', models.IntegerField(default=0)),
                ('sp', models.IntegerField(default=0)),
                ('gddr', models.IntegerField(default=0)),
                ('memory_c', models.IntegerField(default=0)),
                ('memory_v', models.IntegerField(default=0)),
                ('memory_b', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
