# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-08 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('manufacturer', models.CharField(max_length=10)),
                ('socket', models.CharField(max_length=20)),
                ('nm', models.IntegerField()),
                ('core', models.CharField(max_length=5)),
                ('thread', models.IntegerField()),
                ('clock', models.FloatField()),
                ('l2', models.IntegerField()),
                ('l3', models.IntegerField()),
                ('bit', models.CharField(max_length=10)),
                ('tdp', models.IntegerField()),
                ('gpu_name', models.CharField(max_length=100)),
                ('gpu_core', models.IntegerField()),
                ('etc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('capacity', models.CharField(max_length=10)),
                ('sata', models.CharField(max_length=20)),
                ('rpm', models.IntegerField()),
                ('buffer', models.IntegerField()),
                ('width', models.IntegerField()),
                ('thickness', models.CharField(max_length=20)),
                ('noise', models.IntegerField()),
                ('etc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mainboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=20)),
                ('socket', models.CharField(max_length=20)),
                ('chipset', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=20)),
                ('phase', models.IntegerField()),
                ('ddr', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('vga_connect', models.IntegerField()),
                ('pcie_slot', models.IntegerField()),
                ('sata3', models.IntegerField()),
                ('m_2_slot', models.IntegerField()),
                ('output', models.IntegerField()),
                ('ps_2', models.IntegerField()),
                ('usb_2_0', models.IntegerField()),
                ('usb_3_1_1', models.IntegerField()),
                ('usb_3_1_2', models.IntegerField()),
                ('etc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=20)),
                ('standard', models.CharField(max_length=10)),
                ('w', models.IntegerField()),
                ('fan_size', models.IntegerField()),
                ('fan_num', models.IntegerField()),
                ('pfc', models.CharField(max_length=10)),
                ('rail', models.CharField(max_length=10)),
                ('a', models.IntegerField()),
                ('pin4_ide', models.IntegerField()),
                ('sata', models.IntegerField()),
                ('pin6plus2_pci_e', models.IntegerField()),
                ('as_power', models.IntegerField()),
                ('etc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=20)),
                ('ddr', models.IntegerField()),
                ('use', models.CharField(max_length=10)),
                ('count', models.IntegerField()),
                ('heatsink', models.CharField(max_length=10)),
                ('dimm', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('clock', models.IntegerField()),
                ('etc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=20)),
                ('prod_name', models.CharField(max_length=15)),
                ('nm', models.IntegerField()),
                ('clock', models.IntegerField()),
                ('b_clock', models.IntegerField()),
                ('sp', models.IntegerField()),
                ('PCIe', models.CharField(max_length=10)),
                ('gddr', models.IntegerField()),
                ('memory_c', models.IntegerField()),
                ('memory_v', models.IntegerField()),
                ('memory_b', models.IntegerField()),
                ('etc', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
